


#### -------
#### Imports
#### -------


# Standard library imports
import os
from pathlib import Path
import pickle

# Third-party imports
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import pandas as pd
from scipy.stats import gaussian_kde




#### ------------------------
#### Sample Loading
#### ------------------------


def group_sample_data(data_parent_folder: str) -> pd.DataFrame:
    """
    Load and merge per-object morphological and mechanism event data across all samples.
    
    Parameters:
        data_parent_folder (str): Directory path containing sample folders per-replicate.

    Returns:
        pd.DataFrame: Dataframe of merged morphological and event mechanism rows.
    """

    all_data = []
    
    for sample, replicates in sample_groups.items():
        for replicate in replicates:
            folder = Path(data_parent_folder, str(replicate), "processed_data_analysis")
            morphological_csv = Path(folder, "general_morphological_features_per_object.csv")
            mechanism_csv = Path(folder, "fission_fusion_mechanisms.csv")
            if morphological_csv.exists() and mechanism_csv.exists():
                morphological_df = pd.read_csv(morphological_csv)
                fission_fusion_mechanism_df = pd.read_csv(mechanism_csv)
                
                merged_df = pd.merge(morphological_df, fission_fusion_mechanism_df, on=["Label"], how='left')
                
                merged_df['Sample'] = sample 
                merged_df['Replicate'] = replicate
                
                all_data.append(merged_df)
            else:
                print(f"Missing files in {folder}")
                
    return pd.concat(all_data, ignore_index=True) if all_data else pd.DataFrame()


def find_parent_children(graph_data_parent_folder: str, df: pd.DataFrame) -> pd.DataFrame:
    """
    Populate morphological/event mechanism dataframe with predecessor (parent) and successor (children) node information.
    
    Parameters:
        data_parent_folder (str): Directory path containing graph files per-replicate.
        df (pd.DataFrame): Merged morphological and event mechanism dataframe from group_sample_data.

    Returns:
        df (pd.DataFrame): Additional Parent and Children columns where each entry is a list of (frame, object_id).
    """
        
    df = df.copy()
    df['Parents'] = [[] for _ in range(len(df))]
    df['Children'] = [[] for _ in range(len(df))]
    
    for sample, replicates in sample_groups.items():
        for replicate in replicates:
            
            folder = Path(graph_data_parent_folder, str(replicate)) 
            
            with open(Path(folder, 'matching_nx_graph.pickle'), 'rb') as f:
                matching_graph = pickle.load(f)

            mask = df['Replicate'] == replicate
            subset = df.loc[mask] # Series Row extraction of Replicate Data

            parents = []
            children = []
            for _, row in subset.iterrows():
                node_gen = (row['Generation Frame'], row['Label'])
                node_term = (row['Termination Frame'], row['Label'])
                
                child_nodes = list(matching_graph.successors(node_term))
                parent_nodes = list(matching_graph.predecessors(node_gen))

                parents.append(parent_nodes)
                children.append(child_nodes)
   
            df.loc[mask, 'Parents'] = pd.Series(parents, index=subset.index)
            df.loc[mask, 'Children'] = pd.Series(children, index=subset.index)
            
            # df['Children'] = df.apply(lambda row: list(matching_graph.successors((row['Termination Frame'], row['Label']))), axis=1)
            # for object_id, termination_frame in 
            # list(matching_graph.successors((termination_frame, object_id)))
    return df




#### -----------------------------------------
#### Processing Split Ratio Data
#### -----------------------------------------


def get_child_areas(row, df: pd.DataFrame) -> list[float]:
    """
    Return list of child areas for the children listed in row['Children'],
    but only searching within the same Replicate as row['Replicate'] to avoid cross-replicate collisions.

    Parameters:
        row (pd.Series): List of dataframe rows containing Children lists.
        df (pd.DataFrame): Full dataframe generated by find_parent_children.

    Returns:
        areas (list): List of child areas (empty if areas not found).
    """

    children = row.get('Children', []) or []
    rep = row.get('Replicate', None)
    areas = []
    
    for (frame, cid) in children:
        if rep is None:
            child = df[(df['Generation Frame'] == frame) & (df['Label'] == cid)]
        else:
            child = df[(df['Replicate'] == rep) & (df['Generation Frame'] == frame) & (df['Label'] == cid)]
        if not child.empty:
            areas.append(float(child['Area'].values[0]))

    return areas


def _select_region_df(df: pd.DataFrame, region: str) -> pd.DataFrame:
    """
    Helper to pick rows which fall within a given spatial region.

    Parameters:
        df (pd.DataFrame): Input dataframe.
        region (str): Region name to select.

    Returns:
        df (pd.DataFrame): Filtered copy of df corresponding to the specified region.
    """
    
    if region == 'Global':
        return df.copy()
    
    candidates = [
        f"is_{region}",
        f"is_{region.replace(' ', '_')}",
        f"is_{region.replace(' ', '').replace('(', '').replace(')', '')}",
    ]
    
    for c in candidates:
        if c in df.columns:
            if df[c].dtype == bool or df[c].dtype == 'bool':
                return df[df[c].astype(bool)].copy()
    
    if 'Region' in df.columns:
        return df[df['Region'] == region].copy()
    
    return df.copy()




#### -----------------------------------------
#### Post-Fission Area Split Ratio Plotting
#### -----------------------------------------


def split_ratio_kde(df: pd.DataFrame, conditions: list[str], regions_order: list[str], 
                    replicate_col: str = 'Replicate', frame_col: str = 'Termination Frame', split_col: str = 'Split Ratio', 
                    num_splits: int = 5, palette: dict[str, str] | None = None, area_filter: tuple[float, float] | None = None, 
                    figsize_per_col: float = 5, xs_common: np.ndarray | None = None, save_path: str | None = None, bw_adjust: float = 0.5, 
                    show_individual_replicates: bool = True, replicate_alpha: float = 0.2, show_confidence_band: bool = True) -> plt.Figure:
    """    
    Plot replicate-aware KDEs (computes KDEs for each replicate first) of post-fission split ratios across time windows and spatial regions. 
    
    Parameters:
        df (pd.DataFrame): Processed dataframe that must contain a column identifying replicates (e.g., 'Replicate', 'Experiment_ID')
        conditions (list): List of experimental conditions to plot.
        regions_order (list): Ordered list of region names to plot.
        replicate_col (str): Column name identifying biological replicates.
        frame_col (str): Column name indicating event frame type.
        split_col (str): Column name containing split ratio values.
        num_splits (int): Number of temporal windows to partition each condition into for plotting.
        palette (dict, optional): Dictionary mapping condition names to color strings.
        area_filter (tuple, optional): (min_area, max_area) to filter data by.
        figsize_per_col (float): Width (inches) per region column.
        xs_common (np.ndarray, optional): X-axis grid to evaluate KDEs on.
        save_path (str, optional): If provided, save figure to this path.
        bw_adjust (float): Multiplier for KDE bandwidth (Scott=1.0, Tighter < 1, Smoother > 1).
        show_individual_replicates (bool): If True, plot faint KDE for each replicate.
        replicate_alpha (float): Transparency for individual replicate KDEs.
        show_confidence_band (bool): If True, show SEM band around mean KDE.
    
    Returns:
        Figure plot/None.
    """
    
    if palette is None:
        palette = {}
    if xs_common is None:
        xs_common = np.linspace(0, 0.5, 400)
    
    # Verify replicate column exists
    if replicate_col not in df.columns:
        print(f"WARNING: '{replicate_col}' not found in DataFrame. Falling back to pooled analysis.")
        print(f"Available columns: {df.columns.tolist()}")
        replicate_col = None
    
    # Calculate global time windows
    max_frame = None
    for condition in conditions:
        cond_max = int(df[df['Sample'] == condition]['Termination Frame'].max())
        if max_frame is None:
            max_frame = cond_max
        else:
            max_frame = max(max_frame, cond_max)
    time_windows = [(((i-1) * max_frame) / num_splits, (i * max_frame) / num_splits) 
                    for i in range(1, num_splits + 1)]
    
    # Setup grid
    nrows = num_splits
    ncols = len(regions_order)
    fig, axes = plt.subplots(nrows, ncols, 
                             figsize=(figsize_per_col * ncols, 3.5 * nrows),
                             sharex=True, sharey=True)
    
    # Ensure axes is 2D array
    if nrows == 1 and ncols == 1:
        axes = np.array([[axes]])
    elif nrows == 1:
        axes = axes[np.newaxis, :]
    elif ncols == 1:
        axes = axes[:, np.newaxis]
    
    # Plot each time window (rows)
    for row_idx, (start, end) in enumerate(time_windows):
        
        # Plot each region (columns)
        for col_idx, region in enumerate(regions_order):
            ax = axes[row_idx, col_idx]
            
            # Overlay each condition in this subplot
            for condition in conditions:
                cond_color = palette.get(condition, '#333333')
                
                # Filter by condition
                cond_df = df[df['Sample'] == condition].copy()
                
                # Apply area filter
                if area_filter is not None and 'Parent Area' in cond_df.columns:
                    amin, amax = area_filter
                    cond_df = cond_df[(cond_df['Parent Area'] > amin) & (cond_df['Parent Area'] < amax)]
                
                # Filter by region
                region_df = _select_region_df(cond_df, region)
                
                # Filter by time window
                mask = (region_df[frame_col] >= start) & (region_df[frame_col] < end)
                if row_idx == len(time_windows) - 1:
                    mask = (region_df[frame_col] >= start) & (region_df[frame_col] <= end)
                
                windowed_df = region_df.loc[mask].copy()
                

                # REPLICATE-AWARE ANALYSIS
                
                if replicate_col and replicate_col in windowed_df.columns:
                    # Get unique replicates
                    replicates = windowed_df[replicate_col].dropna().unique()
                    
                    if len(replicates) == 0:
                        continue
                    
                    # Compute KDE for each replicate
                    replicate_kdes = []
                    replicate_medians = []
                    
                    for rep in replicates:
                        rep_data = windowed_df[windowed_df[replicate_col] == rep][split_col].dropna()
                        
                        if len(rep_data) < 3:
                            continue
                        
                        try:
                            # Compute KDE for this replicate
                            if bw_adjust != 1.0:
                                kde = gaussian_kde(rep_data, bw_method=lambda x: gaussian_kde.scotts_factor(x) * bw_adjust)
                            else:
                                kde = gaussian_kde(rep_data, bw_method='scott')
                            
                            ys = kde(xs_common)
                            replicate_kdes.append(ys)
                            replicate_medians.append(np.median(rep_data))
                            
                            # Plot individual replicate KDE (faint)
                            if show_individual_replicates:
                                ax.plot(xs_common, ys, color=cond_color, linewidth=1, alpha=replicate_alpha, zorder=1)
                        
                        except Exception as e:
                            print(f"KDE failed for {condition}-{region}-Window{row_idx+1}-Rep{rep}: {e}")
                            continue
                    
                    if len(replicate_kdes) < 1:
                        continue
                    
                    # Convert to array
                    replicate_kdes = np.array(replicate_kdes)
                    replicate_medians = np.array(replicate_medians)
                    
                    # Compute mean and SEM across replicates
                    mean_kde = np.mean(replicate_kdes, axis=0)
                    sem_kde = np.std(replicate_kdes, axis=0, ddof=1) / np.sqrt(len(replicate_kdes))
                    
                    # Plot mean KDE
                    ax.plot(xs_common, mean_kde, color=cond_color, linewidth=1.5, 
                           label=condition if (row_idx==0 and col_idx==0) else None,
                           zorder=3)#, alpha=0.95)
                    
                    # Plot confidence band (SEM)
                    if show_confidence_band and len(replicate_kdes) > 1:
                        ax.fill_between(xs_common, 
                                       mean_kde - sem_kde, 
                                       mean_kde + sem_kde,
                                       color=cond_color, alpha=0.15, zorder=2)
                    
                    # Add median marker (mean of replicate medians)
                    mean_median = np.mean(replicate_medians)
                    # Interpolate KDE value at mean median
                    y_med = np.interp(mean_median, xs_common, mean_kde)
                    ax.plot(mean_median, y_med, marker='o', color=cond_color, 
                           markersize=6, zorder=10, markeredgecolor='white', markeredgewidth=0.5)
                    ax.vlines(mean_median, color=cond_color, ymin=0, ymax=y_med, 
                             linestyle='--', linewidth=1.2, alpha=0.7, zorder=9)
                    
                    # Print replicate info
                    if row_idx == 0 and col_idx == 0:
                        print(f"{condition}: {len(replicate_kdes)} replicates")
                
                else:
                    # FALLBACK: Original pooled analysis if no replicate column
                    data = windowed_df[split_col].dropna()
                    
                    if len(data) < 3:
                        continue
                    
                    try:
                        if bw_adjust != 1.0:
                            kde = gaussian_kde(data, bw_method=lambda x: gaussian_kde.scotts_factor(x) * bw_adjust)
                        else:
                            kde = gaussian_kde(data, bw_method='scott')
                        
                        ys = kde(xs_common)
                        
                        ax.plot(xs_common, ys, color=cond_color, linewidth=1.5, 
                               label=condition if (row_idx==0 and col_idx==0) else None)#,
                               #alpha=0.85)
                        
                        median_val = np.median(data)
                        y_med = kde(median_val)[0]
                        ax.plot(median_val, y_med, marker='o', color=cond_color, markersize=5, zorder=10)
                        ax.vlines(median_val, color=cond_color, ymin=0, ymax=y_med, linestyle='--', linewidth=1.2, alpha=0.9)
                    
                    except Exception as e:
                        print(f"KDE failed for {condition}-{region}-Window{row_idx+1}: {e}")
                        continue
            
            # # Formatting
            # if row_idx == 0:
            #     ax.set_title(region, fontsize=11, fontweight='bold')
            
            # if col_idx == 0:
            #     window_label = f'Window {row_idx+1}\n({int(start)}–{int(end)})'
            #     ax.set_ylabel(window_label + '\nDensity', fontsize=10)
            
            # if row_idx == nrows - 1:
            #     ax.set_xlabel('Split Ratio', fontsize=10)

            ax.set_xlim(0, 0.5)
            ax.xaxis.set_major_locator(MultipleLocator(0.1))
            ax.yaxis.set_major_locator(MultipleLocator(1.0))
            # ax.grid(alpha=0.13)
            ax.tick_params(axis='both', direction='out', labelsize=13, width=1, length=6)
            
            # # Legend only in top-left
            # if row_idx == 0 and col_idx == 0:
            #     legend = ax.legend(fontsize=8, loc='upper right', framealpha=0.9)
            #     legend.set_zorder(20)
    
    # # Figure title
    # if replicate_col and replicate_col in df.columns:
    #     suptitle = f"{fig_title_prefix} — Split Ratio Distribution by Time Window (Replicate-Aware)"
    # else:
    #     suptitle = f"{fig_title_prefix} — Split Ratio Distribution by Time Window (Pooled)"
    
    # fig.suptitle(suptitle, fontsize=14, fontweight='bold')

    # Set y-axis limit automatically
    global_ymax = 0
    for ax_row in axes:
        for ax in ax_row:
            y0, y1 = ax.get_ylim()
            global_ymax = max(global_ymax, y1)
    global_ymax += 1
    
    # Apply the same y-limit to all subplots
    for ax_row in axes:
        for ax in ax_row:
            ax.set_ylim(0, global_ymax)
            
    plt.tight_layout()#(rect=[0, 0.03, 1, 0.96])
    
    if save_path:
        fig.savefig(save_path, dpi=500, bbox_inches='tight', transparent=True)
        print(f"\nFigure saved to: {save_path}")
    
    return fig



def plot_median_vs_time_summary(df: pd.DataFrame, conditions: list[str], regions_order: list[str],
                                replicate_col: str = 'Replicate', frame_col: str = 'Termination Frame', split_col: str = 'Split Ratio', num_splits: int = 5, 
                                palette: dict[str, str] | None = None, area_filter: tuple[float, float] | None = None, 
                                save_path: str | None = None, figsize_per_col: float = 5, 
                                time_unit: str = 'minutes', frame_interval: float = 0.5, 
                                xlim: list[float] | None = None, ylim: list[float] | None = None) -> None:
    """
    Plot median split ratio vs time window for each region (3 separate subplots).

    Parameters:
        df (pd.DataFrame): Processed dataframe that must contain a column identifying replicates (e.g., 'Replicate', 'Experiment_ID')
        conditions (list): List of experimental conditions to plot.
        regions_order (list): Ordered list of region names to plot.
        replicate_col (str): Column name identifying biological replicates.
        frame_col (str): Column name indicating event frame type.
        split_col (str): Column name containing split ratio values.
        num_splits (int): Number of temporal windows to partition each condition into for plotting.
        palette (dict, optional): Dictionary mapping condition names to color strings.
        area_filter (tuple, optional): (min_area, max_area) to filter data by.
        save_path (str, optional): If provided, save figure to this path.
        figsize_per_col (float): Width (inches) per region column.
        time_unit (str): Display time in 'frames', 'seconds', or 'minutes' (default: 'minutes').
        frame_interval (float): Time interval between frames in seconds (default: 0.5).
        xlim (list): X-axis limits.
        ylim (list): Y-axis limits.
    
    Returns:
        None.
    """

    if palette is None:
        palette = {}
    
    # Validate time_unit
    if time_unit not in ['frames', 'seconds', 'minutes']:
        raise ValueError("time_unit must be 'frames', 'seconds', or 'minutes'")
    
    # Helper function to convert frames to desired time unit
    def convert_time(frames):
        if time_unit == 'frames':
            return frames
        elif time_unit == 'seconds':
            return frames * frame_interval
        elif time_unit == 'minutes':
            return frames * frame_interval / 60.0
    
    # Get x-axis label
    time_labels = {
        'frames': 'Time Window Center (Frames)',
        'seconds': 'Time Window Center (Seconds)',
        'minutes': 'Time Window Center (Minutes)'
    }
    
    # Helper function to select region
    def _select_region_df_local(df_in, region):
        if region == 'Global':
            return df_in.copy()
        
        candidates = [
            f"is_{region}",
            f"is_{region.replace(' ', '_')}",
            f"is_{region.replace(' ', '').replace('(', '').replace(')', '')}",
        ]
        
        for c in candidates:
            if c in df_in.columns:
                if df_in[c].dtype == bool or df_in[c].dtype == 'bool':
                    return df_in[df_in[c].astype(bool)].copy()
        
        if 'Region' in df_in.columns:
            return df_in[df_in['Region'] == region].copy()
        
        return df_in.copy()
    
    # Calculate global time windows
    max_frame = None
    for condition in conditions:
        cond_max = int(df[df['Sample'] == condition]['Termination Frame'].max())
        if max_frame is None:
            max_frame = cond_max
        else:
            max_frame = max(max_frame, cond_max)
    
    time_windows = [(((i-1) * max_frame) / num_splits, (i * max_frame) / num_splits) 
                    for i in range(1, num_splits + 1)]
    window_positions = [convert_time(end) for start, end in time_windows] 
    
    # Create figure - match original dimensions
    ncols = len(regions_order)
    fig, axes = plt.subplots(1, ncols, 
                             figsize=(figsize_per_col * ncols, 3.5),  # Match original height
                             sharey=True)
    
    # Ensure axes is array if only one region
    if ncols == 1:
        axes = [axes]
    
    # For each region
    for col_idx, region in enumerate(regions_order):
        ax = axes[col_idx]
        
        # For each condition
        for condition in conditions:
            cond_color = palette.get(condition, '#333333')
            
            # Storage for medians across time windows
            medians_by_window = []
            sems_by_window = []
            
            # For each time window
            for start, end in time_windows:
                # Filter data
                cond_df = df[df['Sample'] == condition].copy()
                
                if area_filter is not None and 'Parent Area' in cond_df.columns:
                    amin, amax = area_filter
                    cond_df = cond_df[(cond_df['Parent Area'] > amin) & (cond_df['Parent Area'] < amax)]
                
                region_df = _select_region_df_local(cond_df, region)
                
                mask = (region_df[frame_col] >= start) & (region_df[frame_col] <= end)
                windowed_df = region_df.loc[mask].copy()
                
                # Compute replicate-aware median
                if replicate_col and replicate_col in windowed_df.columns:
                    replicates = windowed_df[replicate_col].dropna().unique()
                    replicate_medians = []
                    
                    for rep in replicates:
                        rep_data = windowed_df[windowed_df[replicate_col] == rep][split_col].dropna()
                        if len(rep_data) >= 3:
                            replicate_medians.append(np.median(rep_data))
                    
                    if len(replicate_medians) > 0:
                        mean_median = np.mean(replicate_medians)
                        sem_median = np.std(replicate_medians, ddof=1) / np.sqrt(len(replicate_medians)) if len(replicate_medians) > 1 else 0
                        medians_by_window.append(mean_median)
                        sems_by_window.append(sem_median)
                    else:
                        medians_by_window.append(np.nan)
                        sems_by_window.append(np.nan)
                else:
                    # Fallback: pooled median
                    data = windowed_df[split_col].dropna()
                    if len(data) >= 3:
                        medians_by_window.append(np.median(data))
                        sems_by_window.append(0)
                    else:
                        medians_by_window.append(np.nan)
                        sems_by_window.append(0)
            
            # Plot line with error bars
            medians_by_window = np.array(medians_by_window)
            sems_by_window = np.array(sems_by_window)
            
            # Remove debug output for cleaner graphs
            # print(f"{condition} - {region}:")
            # print(f"  Window positions: {window_positions}")
            # print(f"  Medians: {medians_by_window}")
            # print(f"  SEMs: {sems_by_window}")
            # print(f"  Any NaN? {np.any(np.isnan(medians_by_window))}")
            
            ax.errorbar(window_positions, medians_by_window, yerr=sems_by_window,
                       color=cond_color, marker='o', markersize=6, linewidth=1.5,
                       capsize=4, capthick=1.5, label=condition, zorder=3)
        
        # Formatting - match original style
        # Removed title - will be set globally
        # ax.set_xlabel(time_labels[time_unit], fontsize=10)
        # if col_idx == 0:
        #     ax.set_ylabel('Median Split Ratio', fontsize=10)
        
        # Let matplotlib auto-scale the y-axis
        # ax.yaxis.set_major_locator(MultipleLocator(0.05))
        # ax.grid(alpha=0.13)  # Match original grid style
        ax.tick_params(axis='both', direction='out', labelsize=13, width=1, length=6)
        if xlim is not None:
            ax.set_xlim(xlim[0],xlim[1])
        if ylim is not None:
            ax.set_ylim(ylim[0],ylim[1])
        ax.grid(axis='both', linestyle='--', alpha=0.3)
        # if col_idx == 0:
        #     ax.legend(fontsize=8, loc='upper left', framealpha=0.9)
    
    plt.tight_layout()
    
    if save_path:
        fig.savefig(save_path, dpi=500, bbox_inches='tight', transparent=True)
        print(f"\nMedian summary figure saved to: {save_path}")
    else:
        plt.show()



if __name__=="__main__":
    # Colour Palettes
    palette = {
            'WT': '#FF6000',
            'IRSp53 KO': '#2E58FF',
            '9.6mW': '#FAA3FA',
            '27mW': '#E15EF9',
            '128.7mW': '#8303C8',
            '252.3mW': '#330084'
        }
    
    # Condition Name: Replicate Folder IDs
    sample_groups = {
                    "WT": [5, 7, 10],
                    "IRSp53 KO": [33, 34, 35],
                    "9.6mW": [17, 18, 20],
                    "27mW": [25, 26, 28],
                    "128.7mW": [1, 2, 4],
                    "252.3mW": [21, 22, 23]
                    }

    # Load Data
    data_folder = Path(os.getcwd(), "processed_outputs_60secbin/")

    mechanism_df = group_sample_data(data_parent_folder=data_folder)
    mechanism_df = find_parent_children(Path('segmentation_data'), mechanism_df)

    idx = mechanism_df.groupby(['Replicate', 'Label'])['Time (Seconds)'].idxmax()
    final_time_row = mechanism_df.loc[idx].reset_index(drop=True)
    fission_df = final_time_row[final_time_row['Termination Mechanism'] == 'Fission'].copy()

    # Calculations
    fission_df['Child Areas'] = fission_df.apply(lambda row: get_child_areas(row, mechanism_df), axis=1)
    fission_df['Parent Area'] = fission_df['Area'].astype(float)
    fission_df['Total Child Area'] = fission_df['Child Areas'].apply(lambda x: sum(x) if x else 0.0)
    fission_df['Area Conservation Ratio'] = fission_df.apply(lambda r: (r['Total Child Area'] / r['Parent Area']) if (r['Parent Area'] and not np.isnan(r['Parent Area'])) else np.nan, axis=1)
    fission_df['Split Symmetry'] = fission_df['Child Areas'].apply(lambda areas: min(areas)/max(areas) if len(areas) == 2 else None)
    fission_df['Split Ratio'] = fission_df['Child Areas'].apply(lambda areas: min(areas)/(min(areas)+max(areas)) if len(areas) == 2 else None)
    fission_df['Delta Area'] = fission_df['Total Child Area'] - fission_df['Parent Area']
    fission_df['Number of Children'] = fission_df['Children'].apply(lambda c: len(c) if c else 0)



    regions_order = ["Global", "Telenuclear", "Perinuclear"]

    # Figure 1: Irradiation conditions (REPLICATE-AWARE)
    conditions_1 = ['9.6mW', '27mW', '128.7mW', '252.3mW']
    fig1 = split_ratio_kde(
        df=fission_df,
        conditions=conditions_1,
        regions_order=regions_order,
        replicate_col='Replicate',
        frame_col='Termination Frame',
        split_col='Split Ratio',
        num_splits=5,
        palette=palette,
        area_filter=None,
        figsize_per_col=5,
        save_path="Figure_SplitRatio_Irradiation_9.6mW-252.3mW_ReplicateAware.png",
        bw_adjust=0.5,
        show_individual_replicates=False,  # Show faint individual replicate KDEs
        replicate_alpha=0.2,  # Transparency for individual replicates
        show_confidence_band=True  # Show SEM band
    )
    plt.show()

    # Figure 2: WT vs IRSp53 KO (REPLICATE-AWARE)
    conditions_2 = ['WT', 'IRSp53 KO']
    fig2 = split_ratio_kde(
        df=fission_df,
        conditions=conditions_2,
        regions_order=regions_order,
        replicate_col='Replicate',
        frame_col='Termination Frame',
        split_col='Split Ratio',
        num_splits=5,
        palette=palette,
        area_filter=None,
        figsize_per_col=5,
        save_path="Figure_SplitRatio_WT_vs_IRSp53KO_ReplicateAware.png",
        bw_adjust=0.5,
        show_individual_replicates=False,
        show_confidence_band=True
    )
    plt.show()




    # Summary plot 1: Irradiation conditions (in MINUTES)
    fig_summary1 = plot_median_vs_time_summary(
        df=fission_df,
        conditions=conditions_1,
        regions_order=regions_order,
        replicate_col='Replicate',
        frame_col='Termination Frame',
        split_col='Split Ratio',
        num_splits=5,
        palette=palette,
        area_filter=None,
        figsize_per_col=5,
        save_path="Summary_Median_Irradiation_9.6mW-252.3mW.png",
        time_unit='minutes',
        frame_interval=0.5,
        xlim=[0,30],
        ylim=[0,0.3]
    )
    plt.show()

    # Summary plot 2: WT vs IRSp53 KO
    fig_summary2 = plot_median_vs_time_summary(
        df=fission_df,
        conditions=conditions_2,
        regions_order=regions_order,
        replicate_col='Replicate',
        frame_col='Termination Frame',
        split_col='Split Ratio',
        num_splits=5,
        palette=palette,
        area_filter=None,
        figsize_per_col=5,
        save_path="Summary_Median_WT_vs_IRSp53KO.png",
        time_unit='minutes',
        frame_interval=0.5,
        xlim=[0,12],
        ylim=[0,0.35]
    )
    plt.show()