name: mitodynamicsim
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy==6.0.1
  - ipython
  - jupyterlab
  - matplotlib>=3.7
  - networkx==3.3
  - numpy<2.0
  - pygame
  - python==3.11.8
  - scipy
  - pillow
  - pyyaml
  - porespy==2.4.1
  - pytorch==2.1.2
  - torchvision==0.16.1
  - tqdm
  - scikit-image==0.24.0
  - scikit-learn
  - opencv==4.10.0
  - napari
  - pypardiso
  - cupy
  - pymunk==6.8.1
  - pyqt
