# Dictionary to map original keys to descriptive labels
label_map = {'background_color': 'Background Color',
             'base_color': 'Base Color',
             'chain_link_color': 'Chain Link Color',
             'contact_site_color': 'Contact Site Color',
             'outer_mem_color': 'Outer Membrane Color',
             'outer_mem_leading_edge_color': 'Outer Membrane Leading Edge Color',
             'idle_color': 'Idle Mitochondria Color',
             'leading_edge_color': 'Leading Edge Color',
             'peri_color': 'Perinucleus Color',
             'peri_init_color': 'Initial Perinuclear Color',
             'peri_migr_color': 'Perinuclear Migration Color?',
             'ball_mass_mult': 'Ball Mass Multiplier',
             'len_adder': 'Length Addition',
             'mito_ang_range': 'Mitochondria Angle Range',
             'mito_ball_radius': 'Mitochondria Ball Radius',
             'mito_chain_len_range': 'Range of Mitochondrial Chain Length',
             'num_chains_range': 'Range for Number of Chains?',
             'num_nuc_chains': 'Number of Nuclear Chains?',
             'nuc_interp_points': 'Nuclear Interpolation Points',
             'nuc_points_sample': 'Nuclear Points to Sample',
             'nuc_rad_range': 'Range of Nucleus Radius',
             'nuc_scale_factor_range': 'Nucleus Shape Scale Factor',
             'num_tendrils': 'Number of Tendrils',
             'tendril_length_range': 'Range of Tendril Lengths',
             'balls_in_outer_mem': 'Number of Outer Membrane Balls',
             'leading_edge_length': 'Length of Leading Edge',
             'nuc_mem_rad': 'Nuclear Membrane Radius',
             'outer_mem_ball_mass': 'Outer Membrane Ball Mass',
             'outer_mem_ball_rad': 'Outer Membrane Ball Radius',
             'outer_mem_min_dist_to_center': 'Minimum Distance of Center to Outer Membrane',
             'display_type': 'Display Visualisation Type',
             'show_target_lines': 'Show Target Lines',
             'target_line_color': 'Target Line Color',
             'save_data': 'Save?',
             'save_path': 'Save Path',
             'sim_length_seconds': 'Simulation Length',
             'sim_name_prefix': 'Simulation Name Prefix',
             'fps': 'Frames Per Second',
             'height': 'Simulation Screen Height',
             'physics_steps_per_frame': 'Physics Steps Per Frame',
             'scale_factor': 'Window Scale Factor',
             'space_damping': 'Space Damping',
             'space_gravity': 'Space Gravity',
             'width': 'Simulation Screen Width',
             'fps_limiter': 'FPS Limiter',
             'debug_text': 'Show Debug Text?',
             'chain_link_size': 'Size of Chain Link',
             'fission_site_color': 'Fission Site Color',
             'random_target_color': 'Random Target Color',
             'goal_idle_exit_time': 'Goal Idle Exit Time',
             'goal_idle_new_goal_idle_factor': 'Goal Idle New Goal Idle Factor',
             'goal_idle_new_goal_leading_edge_factor': 'Goal Idle New Goal Leading Edge Factor',
             'goal_idle_new_goal_peri_migr_factor': 'Goal Idle New Goal Peri Migr Factor',
             'goal_leading_edge_exit_range': 'Goal Leading Edge Exit Range',
             'goal_leading_edge_distance_till_close': 'Goal Leading Edge Distance Till Close',
             'goal_leading_edge_sepcial_same_goal_fusion_factor': 'Goal Leading Edge Special Same Goal Fusion Factor',
             'goal_peri_migr_exit_range': 'Goal Peri Migr Exit Range',
             'goal_peri_migr_distance_till_close': 'Goal Peri Migr Distance Till Close',
             'goal_peri_migr_sepcial_same_goal_fusion_factor': 'Goal Peri Migr Special Same Goal Fusion Factor',
             'goal_random_target_exit_range': 'Goal Random Target Exit Range',
             'goal_random_target_distance_till_close': 'Goal Random Target Distance Till Close',
             'goal_random_target_special_same_goal_fusion_factor': 'Goal Random Target Special Same Goal Fusion Factor',
             'perturber_val_low': 'Perturber Value Low',
             'perturber_val_high': 'Perturber Value High',
             'perturber_perturb_max_mag': 'Perturber Perturb Max Magnitude',
             'perturber_period_low': 'Perturber Period Low',
             'perturber_period_high': 'Perturber Period High',
             'perturber_bounce_off_hl': 'Perturber Bounce Off High Low',
             'perturber_allow_oob_recov': 'Perturber Allow Out of Bounds Recovery',
             'goal_peri_init_exit_countdown_init': 'Goal Peri Init Exit Countdown Init',
             'idle_repel_func_vars': 'Idle Repel Function Vars',
             'peri_repel_func_vars': 'Peri Repel Function Vars',
             'leading_target_repel_func_vars': 'Leading Target Repel Function Vars',
             'peri_init_force': 'Peri Init Force',
             'peri_brownian': 'Peri Brownian',
             'idle_brownian': 'Idle Brownian',
             'seeker_brownian': 'Seeker Brownian',
             'chance_to_swap': 'Chance to Swap',
             'tip_min_max_diff': 'Tip Min Max Difference',
             'seeker_base_force': 'Seeker Base Force',
             'seeker_per_ball_force_mult': 'Seeker Per Ball Force Multiplier',
             'random_goal_select_idle_chance': 'Random Goal Select Idle Chance',
             'random_goal_select_random_target_chance': 'Random Goal Select Random Target Chance',
             'random_goal_select_leading_edge_chance': 'Random Goal Select Leading Edge Chance',
             'random_goal_select_peri_migr_chance': 'Random Goal Select Peri Migr Chance',
             'fission_limit': 'Fission Limit',
             'min_chain_len': 'Minimum Chain Length',
             'fission_init_lockout': 'Fission Initial Lockout',
             'fission_lockout_range': 'Fission Lockout Range',
             'peri_fission_countdown_range': 'Peri Fission Countdown Range',
             'fission_count_diff_mult': 'Fission Count Difference Multiplier',
             'fission_mult_range': 'Fission Multiplier Range',
             'fission_limit_diff_mult': 'Fission Limit Difference Multiplier',
             'peri_fission_count_diff_mult': 'Peri Fission Count Difference Multiplier',
             'peri_fission_mult_range': 'Peri Fission Multiplier Range',
             'fusion_lockout_alpha': 'Fusion Lockout Alpha',
             'fusion_lockout_beta': 'Fusion Lockout Beta',
             'path_len_self_fussion_peri_only': 'Path Length for Self Fusion in Peri Only Chains',
             'chance_peri_fussion': 'Chance for Peri Only Fusion to Fail',
             'dist_from_edge_fussion': 'Distance from Edge of Chain to Allow Fusion',
             'chance_single_lockout_fusion_fail': 'Chance for Single Lockout Fusion to Fail',
             'chance_base_fussion_fail': 'Base Chance for Fusion to Fail',
             'shape_choices': 'Choice of Outer Membrane Shape'
             }

# Dictionary to match third level key groupings in parameters.yaml file
group_map = {'fission_parameters': ['fission_limit', 'min_chain_len', 'fission_init_lockout', 'fission_lockout_range', 'peri_fission_countdown_range',
                                    'fission_count_diff_mult', 'fission_mult_range', 'fission_limit_diff_mult', 'peri_fission_count_diff_mult',
                                    'peri_fission_mult_range'],
             'fusion_parameters': ['fusion_lockout_alpha', 'fusion_lockout_beta', 'path_len_self_fussion_peri_only', 'chance_peri_fussion',
                                   'dist_from_edge_fussion', 'chance_single_lockout_fusion_fail', 'chance_base_fussion_fail'],
             'general_color_parameters': ['background_color', 'base_color', 'chain_link_color', 'contact_site_color', 'outer_mem_color', 'outer_mem_leading_edge_color'],
             'goal_parameters': ['goal_idle_exit_time', 'goal_idle_new_goal_idle_factor', 'goal_idle_new_goal_leading_edge_factor', 'goal_idle_new_goal_peri_migr_factor',
                         'goal_leading_edge_exit_range', 'goal_leading_edge_distance_till_close', 'goal_leading_edge_sepcial_same_goal_fusion_factor',
                         'goal_peri_migr_exit_range', 'goal_peri_migr_distance_till_close', 'goal_peri_migr_sepcial_same_goal_fusion_factor',
                         'goal_random_target_exit_range', 'goal_random_target_distance_till_close', 'goal_random_target_special_same_goal_fusion_factor'],
             'goal_color_parameters': ['idle_color', 'leading_edge_color', 'peri_color', 'peri_init_color', 'peri_migr_color', 'fission_site_color', 'random_target_color'],
             'goal_repel_parameters': ['goal_peri_init_exit_countdown_init', 'idle_repel_func_vars', 'peri_repel_func_vars', 'leading_target_repel_func_vars',
                               'peri_init_force', 'peri_brownian', 'idle_brownian', 'seeker_brownian', 'chance_to_swap', 'tip_min_max_diff',
                               'seeker_base_force', 'seeker_per_ball_force_mult'],
             'goal_select_parameters': ['random_goal_select_idle_chance', 'random_goal_select_random_target_chance', 'random_goal_select_leading_edge_chance', 'random_goal_select_peri_migr_chance'],
             'mitochondria_parameters': ['ball_mass_mult', 'len_adder', 'mito_ang_range', 'mito_ball_radius', 'mito_chain_len_range', 'num_chains_range', 'num_nuc_chains'],
             'nucleus_parameters': ['nuc_interp_points', 'nuc_points_sample', 'nuc_rad_range', 'nuc_scale_factor_range', 'num_tendrils', 'tendril_length_range'],
             'outer_membrane_parameters': ['balls_in_outer_mem', 'leading_edge_length', 'nuc_mem_rad', 'outer_mem_ball_mass', 'outer_mem_ball_rad', 'outer_mem_min_dist_to_center', 'shape_choices'],
             'perturber_parameters': ['perturber_val_low', 'perturber_val_high', 'perturber_perturb_max_mag', 'perturber_period_low', 'perturber_period_high',
                              'perturber_bounce_off_hl', 'perturber_allow_oob_recov'],
             'render_display_parameters': ['display_type', 'show_target_lines', 'target_line_color', 'debug_text', 'chain_link_size'],
             'save_simulation_parameters': ['save_data', 'save_path', 'sim_length_seconds', 'sim_name_prefix'],
             'space_world_parameters': ['fps', 'height', 'physics_steps_per_frame', 'scale_factor', 'space_damping', 'space_gravity', 'width', 'fps_limiter']
             }

# Dictionary to group parameters under different subheadings
group_label_map = {'fission_parameters': 'Fission Parameters',
                   'fusion_parameters': 'Fusion Parameters',
                   'general_color_parameters': 'General Colors',
                   'goal_parameters': 'Goal Parameters',
                   'goal_color_parameters': 'Goal Color Parameters',
                   'goal_repel_parameters': 'Goal Repel Parameters',
                   'goal_select_parameters': 'Goal Select Parameters',
                   'mitochondria_parameters': 'Mitochondria Parameters',
                   'nucleus_parameters': 'Nucleus Parameters',
                   'outer_membrane_parameters': 'Outer Membrane Parameters',
                   'perturber_parameters': 'Perturber Parameters',
                   'render_display_parameters': 'Render Display Parameters',
                   'save_simulation_parameters': 'Save Simulation Parameters',
                   'space_world_parameters': 'Space/World Parameters'
                   }

# Check if parameter key contains "color" for color parameters
color_parameters = [key for key in label_map.keys() if 'color' in key.lower()]


# Dictionary to map original keys to pre-defined tooltips
tooltips = {'background_color': 'Background Color',
            'base_color': 'Base Color',
            'chain_link_color': 'Chain Link Color',
            'contact_site_color': 'Contact Site Color',
            'outer_mem_color': 'Outer Membrane Color',
            'outer_mem_leading_edge_color': 'Outer Membrane Leading Edge Color',
            'idle_color': 'Idle Mitochondria Color',
            'leading_edge_color': 'Leading Edge Color',
            'peri_color': 'Perinucleus Color',
            'peri_init_color': 'Initial Perinuclear Color',
            'peri_migr_color': 'Perinuclear Migration Color?',
            'ball_mass_mult': 'Ball Mass Multiplier',
            'len_adder': 'Length Addition',
            'mito_ang_range': 'Mitochondria Angle Range',
            'mito_ball_radius': 'Mitochondria Ball Radius',
            'mito_chain_len_range': 'Range of Mitochondrial Chain Length',
            'num_chains_range': 'Range for Number of Chains?',
            'num_nuc_chains': 'Number of Nuclear Chains?',
            'nuc_interp_points': 'Nuclear Interpolation Points',
            'nuc_points_sample': 'Nuclear Points to Sample',
            'nuc_rad_range': 'Range of Nucleus Radius',
            'nuc_scale_factor_range': 'Nucleus Shape Scale Factor',
            'num_tendrils': 'Number of Tendrils',
            'tendril_length_range': 'Range of Tendril Lengths',
            'balls_in_outer_mem': 'Number of Outer Membrane Balls',
            'leading_edge_length': 'Length of Leading Edge',
            'nuc_mem_rad': 'Nuclear Membrane Radius',
            'outer_mem_ball_mass': 'Outer Membrane Ball Mass',
            'outer_mem_ball_rad': 'Outer Membrane Ball Radius',
            'outer_mem_min_dist_to_center': 'Minimum Distance of Center to Outer Membrane',
            'display_type': 'Display Visualisation Type',
            'show_target_lines': 'Show Target Lines',
            'target_line_color': 'Target Line Color',
            'save_data': 'Save?',
            'save_path': 'Save Path',
            'sim_length_seconds': 'Simulation Length',
            'sim_name_prefix': 'Simulation Name Prefix',
            'fps': 'Frames Per Second',
            'height': 'Simulation Screen Height',
            'physics_steps_per_frame': 'Physics Steps Per Frame',
            'scale_factor': 'Window Scale Factor',
            'space_damping': 'Space Damping',
            'space_gravity': 'Space Gravity',
            'width': 'Simulation Screen Width',
            'fps_limiter': 'FPS Limiter',
            'debug_text': 'Show Debug Text?',
            'chain_link_size': 'Size of Chain Link',
            'fission_site_color': 'Fission Site Color',
            'random_target_color': 'Random Target Color',
            'goal_idle_exit_time': 'Goal Idle Exit Time',
            'goal_idle_new_goal_idle_factor': 'Goal Idle New Goal Idle Factor',
            'goal_idle_new_goal_leading_edge_factor': 'Goal Idle New Goal Leading Edge Factor',
            'goal_idle_new_goal_peri_migr_factor': 'Goal Idle New Goal Peri Migr Factor',
            'goal_leading_edge_exit_range': 'Goal Leading Edge Exit Range',
            'goal_leading_edge_distance_till_close': 'Goal Leading Edge Distance Till Close',
            'goal_leading_edge_sepcial_same_goal_fusion_factor': 'Goal Leading Edge Special Same Goal Fusion Factor',
            'goal_peri_migr_exit_range': 'Goal Peri Migr Exit Range',
            'goal_peri_migr_distance_till_close': 'Goal Peri Migr Distance Till Close',
            'goal_peri_migr_sepcial_same_goal_fusion_factor': 'Goal Peri Migr Special Same Goal Fusion Factor',
            'goal_random_target_exit_range': 'Goal Random Target Exit Range',
            'goal_random_target_distance_till_close': 'Goal Random Target Distance Till Close',
            'goal_random_target_special_same_goal_fusion_factor': 'Goal Random Target Special Same Goal Fusion Factor',
            'perturber_val_low': 'Perturber Value Low',
            'perturber_val_high': 'Perturber Value High',
            'perturber_perturb_max_mag': 'Perturber Perturb Max Magnitude',
            'perturber_period_low': 'Perturber Period Low',
            'perturber_period_high': 'Perturber Period High',
            'perturber_bounce_off_hl': 'Perturber Bounce Off High Low',
            'perturber_allow_oob_recov': 'Perturber Allow Out of Bounds Recovery',
            'goal_peri_init_exit_countdown_init': 'Goal Peri Init Exit Countdown Init',
            'idle_repel_func_vars': 'Idle Repel Function Vars',
            'peri_repel_func_vars': 'Peri Repel Function Vars',
            'leading_target_repel_func_vars': 'Leading Target Repel Function Vars',
            'peri_init_force': 'Peri Init Force',
            'peri_brownian': 'Peri Brownian',
            'idle_brownian': 'Idle Brownian',
            'seeker_brownian': 'Seeker Brownian',
            'chance_to_swap': 'Chance to Swap',
            'tip_min_max_diff': 'Tip Min Max Difference',
            'seeker_base_force': 'Seeker Base Force',
            'seeker_per_ball_force_mult': 'Seeker Per Ball Force Multiplier',
            'random_goal_select_idle_chance': 'Random Goal Select Idle Chance',
            'random_goal_select_random_target_chance': 'Random Goal Select Random Target Chance',
            'random_goal_select_leading_edge_chance': 'Random Goal Select Leading Edge Chance',
            'random_goal_select_peri_migr_chance': 'Random Goal Select Peri Migr Chance',
            'fission_limit': 'Fission Limit',
            'min_chain_len': 'Minimum Chain Length',
            'fission_init_lockout': 'Fission Initial Lockout',
            'fission_lockout_range': 'Fission Lockout Range',
            'peri_fission_countdown_range': 'Peri Fission Countdown Range',
            'fission_count_diff_mult': 'Fission Count Difference Multiplier',
            'fission_mult_range': 'Fission Multiplier Range',
            'fission_limit_diff_mult': 'Fission Limit Difference Multiplier',
            'peri_fission_count_diff_mult': 'Peri Fission Count Difference Multiplier',
            'peri_fission_mult_range': 'Peri Fission Multiplier Range',
            'fusion_lockout_alpha': 'Fusion Lockout Alpha',
            'fusion_lockout_beta': 'Fusion Lockout Beta',
            'path_len_self_fussion_peri_only': 'Path Length for Self Fusion in Peri Only Chains',
            'chance_peri_fussion': 'Chance for Peri Only Fusion to Fail',
            'dist_from_edge_fussion': 'Distance from Edge of Chain to Allow Fusion',
            'chance_single_lockout_fusion_fail': 'Chance for Single Lockout Fusion to Fail',
            'chance_base_fussion_fail': 'Base Chance for Fusion to Fail'
            }