fission_parameters:
  fission_count_diff_mult: 0.01
  fission_init_lockout: 4
  fission_limit: 4
  fission_limit_diff_mult: 0.02
  fission_lockout_range:
  - 8
  - 50
  fission_mult_range:
  - 0.5
  - 1.5
  min_chain_len: 2
  peri_fission_count_diff_mult: 0.08
  peri_fission_countdown_range:
  - 1
  - 52
  peri_fission_mult_range:
  - 0.5
  - 1.5
fusion_parameters:
  chance_base_fussion_fail: 80
  chance_peri_fussion: 1
  chance_single_lockout_fusion_fail: 97
  dist_from_edge_fussion: 1
  fusion_lockout_alpha: 300
  fusion_lockout_beta: 1.85
  path_len_self_fussion_peri_only: 5
general_color_parameters:
  background_color:
  - 0
  - 0
  - 0
  base_color:
  - 255
  - 255
  - 255
  chain_link_color:
  - 155
  - 155
  - 155
  contact_site_color:
  - 255
  - 0
  - 0
  outer_mem_color:
  - 127
  - 0
  - 255
  outer_mem_leading_edge_color:
  - 0
  - 230
  - 0
goal_color_parameters:
  fission_site_color:
  - 0
  - 255
  - 0
  idle_color:
  - 200
  - 0
  - 0
  leading_edge_color:
  - 0
  - 0
  - 255
  peri_color:
  - 255
  - 255
  - 0
  peri_init_color:
  - 0
  - 255
  - 0
  peri_migr_color:
  - 255
  - 96
  - 208
  random_target_color:
  - 0
  - 255
  - 255
goal_parameters:
  goal_idle_exit_time:
  - 150
  - 400
  goal_idle_new_goal_idle_factor: 1
  goal_idle_new_goal_leading_edge_factor: 1
  goal_idle_new_goal_peri_migr_factor: 1
  goal_leading_edge_distance_till_close: 50
  goal_leading_edge_exit_range:
  - 150
  - 400
  goal_leading_edge_sepcial_same_goal_fusion_factor: 3
  goal_peri_migr_distance_till_close: 50
  goal_peri_migr_exit_range:
  - 150
  - 400
  goal_peri_migr_sepcial_same_goal_fusion_factor: 3
  goal_random_target_distance_till_close: 150
  goal_random_target_exit_range:
  - 150
  - 400
  goal_random_target_special_same_goal_fusion_factor: 3
goal_repel_parameters:
  chance_to_swap: 70
  goal_peri_init_exit_countdown_init: 1000
  idle_brownian:
  - 1
  - 4
  idle_repel_func_vars:
  - 300
  - 70
  - 50
  - 10
  leading_target_repel_func_vars:
  - 400
  - 180
  - 70
  - 20
  peri_brownian:
  - 1
  - 3
  peri_init_force: 1500
  peri_repel_func_vars:
  - 400
  - 70
  - 80
  - 50
  seeker_base_force: 110
  seeker_brownian:
  - 2
  - 4
  seeker_per_ball_force_mult: 0.25
  tip_min_max_diff:
  - 600
  - 200
  - 8
goal_select_parameters:
  random_goal_select_idle_chance: 50
  random_goal_select_leading_edge_chance: 18
  random_goal_select_peri_migr_chance: 22
  random_goal_select_random_target_chance: 10
mitochondria_parameters:
  ball_mass_mult: 0.1
  len_adder: 1
  mito_ang_range:
  - 15
  - 60
  mito_ball_radius: 4
  mito_chain_len_range:
  - 2
  - 19
  num_chains_range:
  - 50
  - 110
  num_nuc_chains_range:
  - 23
  - 37
nucleus_parameters:
  nuc_interp_points: 100
  nuc_points_sample: 18
  nuc_rad_range:
  - 0.7
  - 1
  nuc_scale_factor_range:
  - 0.55
  - 0.9
  num_tendrils_range:
  - 13
  - 20
  tendril_length_range:
  - 1
  - 35
  percent_leading_edge_range:
  - 0.1
  - 0.3
  perecent_peri_seeking_leading: 60
outer_membrane_parameters:
  balls_in_outer_mem: 360
  leading_edge_length: 140
  outer_mem_ball_mass: 10
  outer_mem_ball_rad: 15
  shape_choices:
    blob: true
    triangle: true
  outer_mem_rad_range:
  - 0.72
  - 0.95
  nuc_mem_rad_range:
  - 0.15
  - 0.23
perturber_parameters:
  perturber_allow_oob_recov: true
  perturber_bounce_off_hl: true
  perturber_period_high: 16
  perturber_period_low: 16
  perturber_perturb_max_mag: 0.38
  perturber_val_high: 1.4
  perturber_val_low: 0.6
render_display_parameters:
  chain_link_size: 2
  debug_text: true
  display_type: goal
  show_target_lines: false
  target_line_color:
  - 0
  - 255
  - 255
save_simulation_parameters:
  save_data: true
  save_path: sim_output/
  sim_length_seconds: 32
  sim_name_prefix: depricated
space_world_parameters:
  fps: 16
  fps_limiter: False
  height: 2048
  physics_steps_per_frame: 100
  scale_factor: 1
  space_damping: 1.0e-05
  space_gravity:
  - 0
  - 0
  width: 2048
