"""Dummy parameter descriptions for the YAML editor.
Replace these placeholder strings with real descriptions later.
"""

DESCRIPTIONS = {
    'sim': {
        'fission_parameters.fission_count_diff_mult': 'Scales how strongly the non-perinuclear fission rate changes as the number of active chains drifts from the starting count.',
        'fission_parameters.fission_init_lockout': 'Sets the initial post-creation delay, in simulation seconds before FPS scaling, before a chain can undergo fission.',
        'fission_parameters.fission_limit': 'Defines the minimum chain size required before standard fission is allowed.',
        'fission_parameters.fission_limit_diff_mult': 'Adjusts how much chain length influences the rate at which fission lockouts count down.',
        'fission_parameters.fission_lockout_range': 'Sets the random range of standard fission lockout durations in seconds before FPS conversion.',
        'fission_parameters.fission_mult_range': 'Clamps the global multiplier that speeds up or slows down non-perinuclear fission lockout countdowns.',
        'fission_parameters.min_chain_len': 'Sets the minimum allowed size of each daughter chain after a fission event.',
        'fission_parameters.peri_fission_count_diff_mult': 'Scales how strongly perinuclear fission timing changes as the perinuclear chain size changes from its starting value.',
        'fission_parameters.peri_fission_countdown_range': 'Sets the random countdown range, in seconds before FPS scaling, between attempted perinuclear fission events.',
        'fission_parameters.peri_fission_mult_range': 'Clamps the multiplier applied to the perinuclear fission countdown so it stays within a stable range.',
        'fusion_parameters.chance_base_fussion_fail': 'Sets the base chance that a normal fusion attempt will fail.',
        'fusion_parameters.chance_peri_fussion': 'Sets the failure chance used for peri-only fusion attempts, which are retried frequently.',
        'fusion_parameters.chance_single_lockout_fusion_fail': 'Sets the failure chance for fusion attempts that only have a single lockout condition remaining.',
        'fusion_parameters.dist_from_edge_fussion': 'Defines how far from a chain end a fusion can occur, before any extra random offset is added.',
        'fusion_parameters.fusion_lockout_alpha': 'Provides the alpha shape parameter for the gamma-distributed fusion lockout duration.',
        'fusion_parameters.fusion_lockout_beta': 'Provides the beta scale parameter for the gamma-distributed fusion lockout duration.',
        'fusion_parameters.path_len_self_fussion_peri_only': 'Sets the base path length used when checking self-fusion behavior for perinuclear-only chains.',
        'general_color_parameters.background_color': 'Sets the RGB background color of the simulation display.',
        'general_color_parameters.base_color': 'Sets the fallback RGB color used when no special rendering mode applies.',
        'general_color_parameters.chain_link_color': 'Sets the RGB color used to draw links between connected mitochondrial balls.',
        'general_color_parameters.contact_site_color': 'Sets the color used to draw detected collision or contact sites in the display.',
        'general_color_parameters.outer_mem_color': 'Sets the default RGB color for the outer membrane and non-leading-edge nuclear membrane balls.',
        'general_color_parameters.outer_mem_leading_edge_color': 'Sets the RGB color used to highlight leading-edge membrane balls.',
        'goal_color_parameters.fission_site_color': 'Sets the color used to mark fission-related sites in the visualization.',
        'goal_color_parameters.idle_color': 'Sets the RGB color for chains currently assigned the idle goal.',
        'goal_color_parameters.leading_edge_color': 'Sets the RGB color for chains currently assigned the leading-edge goal.',
        'goal_color_parameters.peri_color': 'Sets the RGB color for chains that are part of the perinuclear region.',
        'goal_color_parameters.peri_init_color': 'Sets the RGB color for chains still in the initial perinuclear-seeking phase.',
        'goal_color_parameters.peri_migr_color': 'Sets the RGB color for chains migrating toward the perinuclear region.',
        'goal_color_parameters.random_target_color': 'Sets the RGB color for chains pursuing a random target.',
        'goal_parameters.goal_idle_exit_time': 'Sets the random frame range for how long a chain remains in the idle goal before changing.',
        'goal_parameters.goal_idle_new_goal_idle_factor': 'Weights how likely a newly fused chain is to receive the idle goal.',
        'goal_parameters.goal_idle_new_goal_leading_edge_factor': 'Weights how likely a newly fused chain is to receive the leading-edge goal.',
        'goal_parameters.goal_idle_new_goal_peri_migr_factor': 'Weights how likely a newly fused chain is to receive the perinuclear-migration goal.',
        'goal_parameters.goal_leading_edge_distance_till_close': 'Defines how close a chain must get to its leading-edge target before it switches to close-in behavior.',
        'goal_parameters.goal_leading_edge_exit_range': 'Sets the random frame range for how long a chain stays in the leading-edge goal.',
        'goal_parameters.goal_leading_edge_sepcial_same_goal_fusion_factor': 'Weights how strongly same-goal fusion outcomes favor assigning the leading-edge goal again.',
        'goal_parameters.goal_peri_migr_distance_till_close': 'Defines how close a chain must get to its perinuclear-migration target before it switches to close-in behavior.',
        'goal_parameters.goal_peri_migr_exit_range': 'Sets the random frame range for how long a chain stays in the perinuclear-migration goal.',
        'goal_parameters.goal_peri_migr_sepcial_same_goal_fusion_factor': 'Weights how strongly same-goal fusion outcomes favor assigning the perinuclear-migration goal again.',
        'goal_parameters.goal_random_target_distance_till_close': 'Defines how close a chain must get to a random target before it switches to close-in behavior.',
        'goal_parameters.goal_random_target_exit_range': 'Sets the random frame range for how long a chain stays in the random-target goal.',
        'goal_parameters.goal_random_target_special_same_goal_fusion_factor': 'Weights how strongly same-goal fusion outcomes favor assigning the random-target goal again.',
        'goal_repel_parameters.chance_to_swap': 'Sets the chance that a chain swaps to the opposite-style goal after reaching its current one instead of choosing a fresh random goal.',
        'goal_repel_parameters.goal_peri_init_exit_countdown_init': 'Sets the initial countdown value before perinuclear-init chains are allowed to leave that startup state.',
        'goal_repel_parameters.idle_brownian': 'Sets the random force range used to add Brownian-like motion to idle chains.',
        'goal_repel_parameters.idle_repel_func_vars': 'Provides the parameter tuple for the repel-force function used by idle-goal behavior.',
        'goal_repel_parameters.leading_target_repel_func_vars': 'Provides the parameter tuple for the repel-force function used by leading-edge target behavior.',
        'goal_repel_parameters.peri_brownian': 'Sets the random force range used to add Brownian-like motion to perinuclear chains.',
        'goal_repel_parameters.peri_init_force': 'Sets the startup force used to push peri-init chains toward the nucleus and disturb the initial state.',
        'goal_repel_parameters.peri_repel_func_vars': 'Provides the parameter tuple for the repel-force function used by perinuclear-goal behavior.',
        'goal_repel_parameters.seeker_base_force': 'Sets the base steering force applied to seeker-style chains before per-ball scaling.',
        'goal_repel_parameters.seeker_brownian': 'Sets the random force range used to add Brownian-like motion to seeker chains.',
        'goal_repel_parameters.seeker_per_ball_force_mult': 'Adds extra steering force for seeker chains based on how many balls they contain.',
        'goal_repel_parameters.tip_min_max_diff': 'Controls the min and max tip force in the perinuclear region and how that force is reduced across additional tips.',
        'goal_select_parameters.random_goal_select_idle_chance': 'Sets the selection weight for assigning the idle goal when a random goal is chosen.',
        'goal_select_parameters.random_goal_select_leading_edge_chance': 'Sets the selection weight for assigning the leading-edge goal when a random goal is chosen.',
        'goal_select_parameters.random_goal_select_peri_migr_chance': 'Sets the selection weight for assigning the perinuclear-migration goal when a random goal is chosen.',
        'goal_select_parameters.random_goal_select_random_target_chance': 'Sets the selection weight for assigning the random-target goal when a random goal is chosen.',
        'mitochondria_parameters.ball_mass_mult': 'Scales mitochondrial ball mass relative to radius during chain generation.',
        'mitochondria_parameters.len_adder': 'Adds extra spacing to the distance between consecutive balls in a mitochondrial chain.',
        'mitochondria_parameters.mito_ang_range': 'Sets the allowable angle range between sequential balls when generating mitochondrial chains.',
        'mitochondria_parameters.mito_ball_radius': 'Sets the radius of each mitochondrial ball used in chains and the nucleus structure.',
        'mitochondria_parameters.mito_chain_len_range': 'Sets the base range for the number of balls in each generated mitochondrial chain before extra random offsets are added.',
        'mitochondria_parameters.num_chains_range': 'Sets the range for how many mitochondrial chains are generated at the start of the simulation.',
        'mitochondria_parameters.num_nuc_chains_range': 'Sets the range for how many generated chains are reassigned to the initial nucleus-seeking group.',
        'nucleus_parameters.nuc_interp_points': 'Sets how many interpolated points are used when constructing the nucleus membrane shape.',
        'nucleus_parameters.nuc_points_sample': 'Sets how many seed points are sampled to generate the nucleus blob shape.',
        'nucleus_parameters.nuc_rad_range': 'Sets the relative radius range used when generating the nucleus outline.',
        'nucleus_parameters.nuc_scale_factor_range': 'Sets the range of ellipse-like scaling factors used to distort the nucleus shape.',
        'nucleus_parameters.num_tendrils_range': 'Sets the random range for how many internal nuclear tendrils are created.',
        'nucleus_parameters.tendril_length_range': 'Sets the random range for the lengths of internal nuclear tendrils.',
        'nucleus_parameters.percent_leading_edge_range': 'Sets the fraction range of mitochondria initially biased toward the leading-edge region.',
        'nucleus_parameters.perecent_peri_seeking_leading': 'Controls what percentage of perinuclear-seeking chains are biased toward the leading direction during goal management.',
        'outer_membrane_parameters.balls_in_outer_mem': 'Sets how many balls are used to build the closed outer membrane body.',
        'outer_membrane_parameters.leading_edge_length': 'Sets how many membrane balls are included in the detected leading-edge segment.',
        'outer_membrane_parameters.outer_mem_ball_mass': 'Sets the mass of each ball in the outer membrane soft body.',
        'outer_membrane_parameters.outer_mem_ball_rad': 'Sets the radius of each ball in the outer membrane soft body.',
        'outer_membrane_parameters.outer_mem_min_dist_to_center': 'Sets the minimum allowed distance between the outer membrane and the cell center when validating generated shapes.',
        'outer_membrane_parameters.outer_mem_rad_range': 'Sets the random radial scale range used for the outer membrane size.',
        'outer_membrane_parameters.nuc_mem_rad_range': 'Sets the random radial scale range used to size the nucleus relative to the screen.',
        'outer_membrane_parameters.shape_choices.blob': 'Enables or disables the blob-shaped outer membrane generator as a possible cell shape.',
        'outer_membrane_parameters.shape_choices.triangle': 'Enables or disables the triangle-like outer membrane generator as a possible cell shape.',
        'outer_membrane_parameters.shape_parameters.blob.interp_points': 'Sets how many interpolated points are used when generating the blob outer membrane shape.',
        'outer_membrane_parameters.shape_parameters.blob.rad_range': 'Sets the local radius variation range used by the blob outer membrane generator.',
        'outer_membrane_parameters.shape_parameters.blob.samples': 'Sets how many seed samples are used to generate the blob outer membrane shape.',
        'outer_membrane_parameters.shape_parameters.blob.xy_translation': 'Sets the positional translation factor applied during blob outer membrane generation.',
        'outer_membrane_parameters.shape_parameters.triangle.interp_points': 'Sets how many interpolated points are used when generating the triangle outer membrane shape.',
        'outer_membrane_parameters.shape_parameters.triangle.samples': 'Sets how many seed samples are used to generate the triangle outer membrane shape.',
        'outer_membrane_parameters.shape_parameters.triangle.xy_translation': 'Sets the positional translation factor applied during triangle outer membrane generation.',
        'perturber_parameters.perturber_allow_oob_recov': 'Controls whether the goal perturber is allowed to recover after moving outside its normal bounds.',
        'perturber_parameters.perturber_bounce_off_hl': 'Controls whether the goal perturber reflects off its configured high and low limits.',
        'perturber_parameters.perturber_period_high': 'Sets the upper bound on the perturber period used for goal steering oscillations.',
        'perturber_parameters.perturber_period_low': 'Sets the lower bound on the perturber period used for goal steering oscillations.',
        'perturber_parameters.perturber_perturb_max_mag': 'Sets the maximum single-step perturbation magnitude for the goal perturber.',
        'perturber_parameters.perturber_val_high': 'Sets the upper bound of the goal perturber output value.',
        'perturber_parameters.perturber_val_low': 'Sets the lower bound of the goal perturber output value.',
        'render_display_parameters.chain_link_size': 'Sets the thickness of the rendered lines between linked mitochondrial balls.',
        'render_display_parameters.debug_text': 'Controls whether the simulation overlays debug text and summary counters on the display.',
        'render_display_parameters.display_type': 'Chooses the main visualization mode used to color chains, such as goal, fission, lockout, or none.',
        'render_display_parameters.show_target_lines': 'Controls whether lines are drawn from seeker chains to their current targets.',
        'render_display_parameters.target_line_color': 'Sets the configured color for target lines, although the current code overrides it with per-goal colors when drawing.',
        'save_simulation_parameters.save_data': 'Controls whether simulation outputs and metadata are written to disk.',
        'save_simulation_parameters.save_path': 'Sets the directory where saved simulation runs and output files are stored.',
        'save_simulation_parameters.sim_length_seconds': 'Sets the target simulation duration in seconds after initialization has completed.',
        'space_world_parameters.fps': 'Sets the simulation frame rate used for timing, countdown scaling, and display pacing.',
        'space_world_parameters.fps_limiter': 'Controls whether display updates are limited to every Nth frame instead of every frame.',
        'space_world_parameters.height': 'Sets the simulation world and render surface height in pixels.',
        'space_world_parameters.physics_steps_per_frame': 'Sets how many physics substeps are executed for each rendered simulation frame.',
        'space_world_parameters.scale_factor': 'Sets the downscaling factor used when displaying the simulation window relative to the internal render size.',
        'space_world_parameters.space_damping': 'Sets the global damping applied by the physics engine to reduce motion over time.',
        'space_world_parameters.space_gravity': 'Sets the global gravity vector used by the physics engine.',
        'space_world_parameters.width': 'Sets the simulation world and render surface width in pixels.',
        'brightness_parameters.mito_brightness_max_var_from_start': 'Sets how far a mitochondrial segment brightness is allowed to vary from its starting value.',
        'brightness_parameters.mito_brightness_period_frames': 'Sets the brightness perturbation period in frames for mitochondrial intensity variation.',
        'brightness_parameters.mito_brightness_range': 'Sets the minimum and maximum brightness values used by the mitochondrial brightness perturber.',
        'brightness_parameters.mito_brightness_single_period_max_range': 'Sets the maximum brightness change allowed within a single perturbation period.',
        'peri_fusion_logic.dist_from_edge_fusion_adder': 'Adds a random extra offset to the allowed fusion distance from a chain edge.',
        'peri_fusion_logic.peri_self_fusion_len_range': 'Sets the random range used for self-fusion path length checks in the perinuclear region.',
    },
    'render': {
        'save_load_params.sim_save_path': 'Sets the parent folder where the renderer looks for the simulation output directory for the selected seed.',
        'save_load_params.out_folder': 'Sets the parent folder where the rendered outputs for each seed are written.',
        'save_load_params.do_compress': 'Controls whether the renderer writes compressed output files for the generated dataset.',
        'render_params.save_rate': 'Sets how many simulation frames are skipped between saved render frames, which controls temporal downsampling.',
        'render_params.render_mult': 'Scales the simulation frame size up for high-resolution intermediate rendering before final output resizing.',
        'render_params.save_mult': 'Scales fission and fusion label coordinates into the final saved output resolution.',
        'render_params.randomness_seed': 'Optionally fixes the renderer random seed so all stochastic render choices are repeatable.',
        'invis_params.invis_num_low': 'Sets the lower bound on how many mitochondrial subsets may be removed to create invisible segments.',
        'invis_params.invis_num_high': 'Sets the upper bound on how many mitochondrial subsets may be removed to create invisible segments.',
        'invis_params.invis_size_low': 'Sets the minimum size of each candidate mitochondrial subset that can be removed from the render.',
        'invis_params.invis_size_high': 'Sets the maximum size of each candidate mitochondrial subset that can be removed from the render.',
        'fission_fusion_locs.shape_choice': 'Chooses the marker shape stamped into the fission and fusion label volumes at each detected event location.',
        'fixed_render_params.bg_noise_blob_size': 'Sets the blob scale used when generating coarse background noise structure.',
        'fixed_render_params.cell_bg_conv': 'Sets the convolution kernel size or strength used when smoothing the cell background layer.',
        'fixed_render_params.cell_bg_glow_central_sigma': 'Sets the sigma of the large central Gaussian used to bias background glow toward the middle of the cell.',
        'fixed_render_params.mito_blob_impact_mult': 'Scales how strongly blob texture modulates the mitochondrial signal.',
        'fixed_render_params.half_render_mult_factor': 'Sets the size reduction factor used for partially rendered mitochondrial nodes.',
        'fixed_render_params.common_peri_area_cutoff': 'Sets the cutoff used to identify a shared perinuclear area during peri-region rendering steps.',
        'fixed_render_params.peri_average_mito_width_add': 'Adds extra width to the average perinuclear mitochondrial signal during peri rendering.',
        'fixed_render_params.render_only_node_keep_probability': 'Sets the probability that a render-only edge node is kept instead of being thinned out.',
        'fixed_render_params.render_only_node_neighbor_add_probability': 'Sets the chance that neighbors of a removed render-only node are also included in the thinning set.',
        'fixed_render_params.set_drop_patience': 'Sets how many failed attempts the renderer will tolerate while searching for removable invisible subsets.',
        'fixed_render_params.leaf_subset_shorten_probability': 'Sets the chance that a subset targeted for removal is shortened when it runs into a leaf node.',
        'fixed_render_params.temporal_blob_size_low': 'Sets the minimum diameter of synthetic temporal blobs added across the video volume.',
        'fixed_render_params.temporal_blob_size_high_base': 'Sets the base maximum diameter of synthetic temporal blobs before any dynamic size increase is added.',
        'fixed_render_params.outer_mem_frame_midpoint_multiplier': 'Controls which mid-video frame is sampled to build the static outer-membrane background layer.',
        'fixed_render_params.base_cell_gaussian_kernel_std': 'Sets the standard deviation of the large Gaussian kernel used to blur the cell background mask.',
        'fixed_render_params.cell_gaussian_floor_fraction': 'Adds a baseline fraction of the blurred cell background so the glow does not fall fully to zero.',
        'fixed_render_params.cell_bg_rescale_high': 'Sets the upper rescale target used when stretching the processed cell background intensity.',
        'fixed_render_params.fusion_fission_dim_window': 'Sets the frame window over which recent fission and fusion events can influence dimming behavior.',
        'fixed_render_params.small_mito_node_threshold': 'Defines the node-count threshold below which a mitochondrion is treated as small for disappearance logic.',
        'fixed_render_params.single_frame_disappear_chance_max': 'Sets the maximum one-frame disappearance chance used for vulnerable small mitochondrial segments.',
        'fixed_render_params.label_fmask_dilation_radius': 'Sets the dilation radius applied to label masks when thickening fission and fusion annotations.',
        'fixed_render_params.label_skeleton_dilation_radius': 'Sets the dilation radius applied to label skeletons to slightly widen annotation traces.',
        'fixed_render_params.mito_blobiness': 'Sets the blob generator roughness used to texture the main mitochondrial signal.',
        'fixed_render_params.temporal_background_fraction': 'Sets how strongly temporal background blobs contribute to the final background intensity.',
        'fixed_render_params.mito_peri_blobiness': 'Sets the blob generator roughness used specifically for perinuclear mitochondrial texture.',
        'fixed_render_params.output_compression_scale': 'Sets the intensity scaling factor used when converting floating-point render outputs into compressed image values.',
        'dynamic_render_params.photon_conversion_low': 'Sets the lower bound for the random photon-conversion factor applied to mitochondrial signal intensity.',
        'dynamic_render_params.photon_conversion_high': 'Sets the upper bound for the random photon-conversion factor applied to mitochondrial signal intensity.',
        'dynamic_render_params.cell_bg_blobiness_parameter_low': 'Sets the lower bound for how strongly blob texture perturbs the cell background.',
        'dynamic_render_params.cell_bg_blobiness_parameter_high': 'Sets the upper bound for how strongly blob texture perturbs the cell background.',
        'dynamic_render_params.bg_blob_impact_factor_low': 'Sets the lower bound for the multiplier that controls how much background blobs affect intensity.',
        'dynamic_render_params.bg_blob_impact_factor_high': 'Sets the upper bound for the multiplier that controls how much background blobs affect intensity.',
        'dynamic_render_params.cell_bg_noise_1_std_low': 'Sets the lower bound for the first candidate standard deviation used for background noise.',
        'dynamic_render_params.cell_bg_noise_1_std_high': 'Sets the upper bound for the first candidate standard deviation used for background noise.',
        'dynamic_render_params.cell_bg_noise_2_std_low': 'Sets the lower bound for the second candidate standard deviation used for background noise.',
        'dynamic_render_params.cell_bg_noise_2_std_high': 'Sets the upper bound for the second candidate standard deviation used for background noise.',
        'dynamic_render_params.cell_bg_std_low': 'Sets the lower bound for the mean or baseline level of the rendered cell background.',
        'dynamic_render_params.cell_bg_std_high': 'Sets the upper bound for the mean or baseline level of the rendered cell background.',
        'dynamic_render_params.cell_blob_factor_low': 'Sets the lower bound for the blobiness factor used to generate coarse cell-background blobs.',
        'dynamic_render_params.cell_blob_factor_high': 'Sets the upper bound for the blobiness factor used to generate coarse cell-background blobs.',
        'dynamic_render_params.mito_thickness_singal_size_low': 'Sets the lower bound for the random thickness adjustment applied to mitochondrial morphology.',
        'dynamic_render_params.mito_thickness_singal_size_high': 'Sets the upper bound for the random thickness adjustment applied to mitochondrial morphology.',
        'dynamic_render_params.airy_mito_kernal_size_low': 'Sets the lower bound for the odd-sized Airy kernel used to spread mitochondrial signal.',
        'dynamic_render_params.airy_mito_kernal_size_high': 'Sets the upper bound for the odd-sized Airy kernel used to spread mitochondrial signal.',
        'dynamic_render_params.peri_singl_width_add_1_low': 'Sets the lower bound for the first candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_singl_width_add_1_high': 'Sets the upper bound for the first candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_singl_width_add_2_low': 'Sets the lower bound for the second candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_singl_width_add_2_high': 'Sets the upper bound for the second candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_singl_width_add_3_low': 'Sets the lower bound for the third candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_singl_width_add_3_high': 'Sets the upper bound for the third candidate extra width added to perinuclear signal.',
        'dynamic_render_params.peri_morph_width_add_low': 'Sets the lower bound for the added width used in the perinuclear morphology mask.',
        'dynamic_render_params.peri_morph_width_add_high': 'Sets the upper bound for the added width used in the perinuclear morphology mask.',
        'dynamic_render_params.peri_morph_kernal_size_low': 'Sets the lower bound for the kernel size used to smooth the perinuclear morphology signal.',
        'dynamic_render_params.peri_morph_kernal_size_high': 'Sets the upper bound for the kernel size used to smooth the perinuclear morphology signal.',
        'dynamic_render_params.photon_conversion_rate_add_peri_glow_low': 'Sets the lower bound for extra photon-conversion intensity added to the perinuclear glow channel.',
        'dynamic_render_params.photon_conversion_rate_add_peri_glow_high': 'Sets the upper bound for extra photon-conversion intensity added to the perinuclear glow channel.',
        'dynamic_render_params.photon_conversion_rate_add_peri_morph_low': 'Sets the lower bound for extra photon-conversion intensity added to the perinuclear morphology channel.',
        'dynamic_render_params.photon_conversion_rate_add_peri_morph_high': 'Sets the upper bound for extra photon-conversion intensity added to the perinuclear morphology channel.',
        'dynamic_render_params.cell_bg_scale_factor_low': 'Sets the lower bound for the random scale factor applied to the cell background.',
        'dynamic_render_params.cell_bg_scale_factor_high': 'Sets the upper bound for the random scale factor applied to the cell background.',
        'dynamic_render_params.background_glow_noise_low': 'Sets the lower bound for the multiplier that adds noise into the background glow.',
        'dynamic_render_params.background_glow_noise_high': 'Sets the upper bound for the multiplier that adds noise into the background glow.',
        'dynamic_render_params.mito_segment_consistent_dimness_low': 'Sets the lower bound for the per-segment dimness multiplier assigned to a sampled frame of mitochondria.',
        'dynamic_render_params.mito_segment_consistent_dimness_high': 'Sets the upper bound for the per-segment dimness multiplier assigned to a sampled frame of mitochondria.',
        'dynamic_render_params.blob_size_add_low': 'Sets the lower bound for the extra size added to temporal blobs beyond the fixed base size.',
        'dynamic_render_params.blob_size_add_high': 'Sets the upper bound for the extra size added to temporal blobs beyond the fixed base size.',
        'dynamic_render_params.num_blobs_low': 'Sets the lower bound for how many temporal blobs are added across the rendered volume.',
        'dynamic_render_params.num_blobs_high': 'Sets the upper bound for how many temporal blobs are added across the rendered volume.',
        'dynamic_render_params.temporal_blob_intensity_mult_low': 'Sets the lower bound for the intensity multiplier applied to temporal blob artifacts.',
        'dynamic_render_params.temporal_blob_intensity_mult_high': 'Sets the upper bound for the intensity multiplier applied to temporal blob artifacts.',
        'dynamic_render_params.peri_signal_kernal_size_low': 'Sets the lower bound for the kernel size used to spread the perinuclear signal channel.',
        'dynamic_render_params.peri_signal_kernal_size_high': 'Sets the upper bound for the kernel size used to spread the perinuclear signal channel.',
        'dynamic_render_params.do_peri_glow_chance': 'Sets the probability that a render sample includes the perinuclear glow pathway instead of using the no-glow branch.',
        'dynamic_render_params.peri_glow_clip_max_low': 'Sets the lower bound for the clip maximum applied to the perinuclear glow channel when glow is enabled.',
        'dynamic_render_params.peri_glow_clip_max_high': 'Sets the upper bound for the clip maximum applied to the perinuclear glow channel when glow is enabled.',
        'dynamic_render_params.peri_morph_clip_max_low': 'Sets the lower bound for the clip maximum applied to the perinuclear morphology channel when glow is enabled.',
        'dynamic_render_params.peri_morph_clip_max_high': 'Sets the upper bound for the clip maximum applied to the perinuclear morphology channel when glow is enabled.',
        'dynamic_render_params.base_mito_clip_max_low': 'Sets the lower bound for the clip maximum applied to the base mitochondrial morphology channel when glow is enabled.',
        'dynamic_render_params.base_mito_clip_max_high': 'Sets the upper bound for the clip maximum applied to the base mitochondrial morphology channel when glow is enabled.',
        'dynamic_render_params.mito_morph_clip_fraction_factor_low': 'Sets the lower bound for the fraction used to clip mitochondrial morphology intensity when glow is enabled.',
        'dynamic_render_params.mito_morph_clip_fraction_factor_high': 'Sets the upper bound for the fraction used to clip mitochondrial morphology intensity when glow is enabled.',
        'dynamic_render_params.max_total_single_low': 'Sets the lower bound for the maximum combined single-frame intensity from perinuclear and mitochondrial channels when glow is enabled.',
        'dynamic_render_params.max_total_single_high': 'Sets the upper bound for the maximum combined single-frame intensity from perinuclear and mitochondrial channels when glow is enabled.',
        'dynamic_render_params.no_glow_peri_glow_clip_max': 'Sets the fixed perinuclear glow clip maximum used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_peri_morph_clip_max': 'Sets the fixed perinuclear morphology clip maximum used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_base_mito_clip_max_low': 'Sets the lower bound for the base mitochondrial clip maximum used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_base_mito_clip_max_high': 'Sets the upper bound for the base mitochondrial clip maximum used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_mito_morph_clip_fraction_factor_low': 'Sets the lower bound for the mitochondrial morphology clip fraction used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_mito_morph_clip_fraction_factor_high': 'Sets the upper bound for the mitochondrial morphology clip fraction used when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_max_total_single_low': 'Sets the lower bound for the maximum combined single-frame intensity when the renderer chooses the no-glow branch.',
        'dynamic_render_params.no_glow_max_total_single_high': 'Sets the upper bound for the maximum combined single-frame intensity when the renderer chooses the no-glow branch.',
        'dynamic_render_params.small_mito_disappear_probability_denominator': 'Controls how aggressively small mitochondria are randomly suppressed by acting as the denominator in disappearance probability logic.',
        'dynamic_render_params.small_mito_disappear_dim_low': 'Sets the lower bound for the dimming factor applied when a small mitochondrion is partially suppressed.',
        'dynamic_render_params.small_mito_disappear_dim_high': 'Sets the upper bound for the dimming factor applied when a small mitochondrion is partially suppressed.',
        'dynamic_render_params.brightness_midpoint_threshold': 'Sets the midpoint threshold used in the brightness mapping that converts simulated values into rendered intensity.',
        'dynamic_render_params.brightness_midpoint_slope': 'Sets the slope of the brightness mapping around the midpoint threshold.',
        'dynamic_render_params.brightness_midpoint_intercept': 'Sets the intercept or baseline offset of the brightness mapping around the midpoint threshold.',
        'dynamic_render_params.mito_peri_blobs_rescale_high': 'Sets the upper rescale target used for blob texture applied to perinuclear mitochondrial regions.',
        'dynamic_render_params.mito_peri_blobs_rescale_low': 'Sets the lower rescale target used for blob texture applied to perinuclear mitochondrial regions.',
    },
}

def get_description(script_name: str, parameter_path: str) -> str:
    return DESCRIPTIONS.get(script_name, {}).get(parameter_path, "TODO: add description")